### ISSUE TITLE
Currently tracking idle users

### ISSUE THREAD

**Issue by pokej6** [wrycu/DiscordCharting#1]
We are currently keeping statistics whenever we poll and see that the user is online with a game open. This means that someone can skew our data by leaving a game open and going idle. We should see if there's a way to check whether a user is idle or active and only track active playtime.

**Comment by wrycu** [comment]
Looks like it is supported in the python API as "is_afk".  This might be a bit more confusing than we initially considered, though, since it's possible for someone to go AFK after playing a game (meaning we can't just completely disregard people who are AFK).

**Comment by pokej6** [comment]
We could add a field to the user table for afk and then make a check similar to when we see whether or not they are playing a game

**Comment by wrycu** [comment]
We could do it without another flag, I think.

We don't add the game if they're AFK on first detection (though that wouldn't really make sense anyway).  Then, if we see them AFK at some later point, we write the end time immediately (even though they still have the game open).

Sound OK?

**Comment by pokej6** [comment]
What if they are playing, go afk, then come back and play more without closing?

**Comment by wrycu** [comment]
When they go AFK, it will mark it as ended (since they were not actively playing).  When they come back, it will be seen as them having just started the game (despite them having had it open), and start a new session.

**Comment by pokej6** [comment]
yes.

**Comment by wrycu** [comment]
Make it happen.

**Comment by pokej6** [comment]
I can't. You're the assignee

**Comment by wrycu** [comment]
I'm working on another chart.  Your turn to get your hands dirty.

**Comment by pokej6** [comment]
Did you commit the changes to the create script?

**Comment by wrycu** [comment]
f11a4fbf3ee9b498b62c1dc7826debe37752774b

**Comment by wrycu** [comment]
Let me know when to stop my instance so we don't get double data.

**Comment by pokej6** [comment]
Fixed this by adding to our conditional check for whether a user is playing a game or not

**Comment by wrycu** [comment]
XREF 837038afe353d936a3f2a9f125a7300198c10746
